export const ActionTypes = {
  //products
  SET_PRODUCTS: "SET_PRODUCTS",
  CREATE_PRODUCTS: "CREATE_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  ADD_PRODUCTS_PENDING: "ADD_PRODUCTS_PENDING",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  UPDATE_USER: "UPDATE_USER",
  GET_PRODUCT_PENDING :"GET_PRODUCT_PENDING",
  // bag
  UPDATE_PAGE: "UPDATE_PAGE",
  ADD_BAG: "ADD_BAG",
  BAG: "BAG",

  // user
  USER_REGISTER_PENDING: "USER_REGISTER_PENDING",
  USER_LOGIN_PENDING: "USER_LOGIN_PENDING",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

  // category
  GET_CATEGORY_PENDING: "GET_CATEGORY_PENDING",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_ERROR: "GET_CATEGORY_ERROR",
};
